### PR TITLE
Only install missing packages

### PR DESCRIPTION
**Pull request by codingjoe**

### CODE REVIEW

**Comment by codingjoe** [comment]
@syphar review?

**Comment by syphar** [comment]
had a look at it. 
I don't like the implementation using diff, grep and sed that much. 

There has to be a cleaner way to check if the package is installed.

**Comment by codingjoe** [comment]
well, not really unless we rewrite everything in python instead of bash. Set operations are way easier to perform in python.

**Comment by codingjoe** [comment]
@syphar better? This is as nice as it gets ;)

**Comment by syphar** [comment]
had another look.. 

this implementation does not feel cleaner, and feels risky since it could break when tlmgr would change the output ... 

So it feels 
- risky 
- unclean 

only for this performance change. 

Python would look better (even it contradicts the heroku buildpack idea, which says we should only use bash). 
But even with Python, it would have to rely on the (ugly) LaTeX command-line tools for packaging ...

**Comment by codingjoe** [comment]
It would also break if tlmgr would change the input. I don't really see where it's unclean or even risky. It's faster and actually allows freezing of the latch version, if you'd drop the update.
I'd even save it feels cleaner not to run updates twice.

**Pull request closed without merging**
